domain_path: /home/ilyas/Documents/Code/EPFL/EST-message-processing-unit/mpu/sw/zed_mpu_platform/export/zed_mpu_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
