// Generated by mpu/hdl/scripts/gen_rrc_pkg.py
// Do not edit manually.

package rrc_pkg;

  localparam int SAMPLES_PER_SYMBOL = 4;
  localparam int SUB_FILTER_TAPS = 11;
  localparam int COEFF_WIDTH = 18;

  // Function to retrieve coefficients
  function automatic logic signed [COEFF_WIDTH-1:0] get_coeff(input int phase, input int tap);
    case (phase)
      0: begin
        case (tap)
          0: return 418;
          1: return 114;
          2: return -1418;
          3: return 3182;
          4: return -4718;
          5: return 61037;
          6: return -4718;
          7: return 3182;
          8: return -1418;
          9: return 114;
          10: return 418;
          default: return '0;
        endcase
      end
      1: begin
        case (tap)
          0: return -132;
          1: return 742;
          2: return -823;
          3: return -1230;
          4: return 11525;
          5: return 53321;
          6: return -10509;
          7: return 3640;
          8: return -532;
          9: return -572;
          10: return 0;
          default: return '0;
        endcase
      end
      2: begin
        case (tap)
          0: return -648;
          1: return 533;
          2: return 1427;
          3: return -7530;
          4: return 33859;
          5: return 33859;
          6: return -7530;
          7: return 1427;
          8: return 533;
          9: return -648;
          10: return 0;
          default: return '0;
        endcase
      end
      3: begin
        case (tap)
          0: return -572;
          1: return -532;
          2: return 3640;
          3: return -10509;
          4: return 53321;
          5: return 11525;
          6: return -1230;
          7: return -823;
          8: return 742;
          9: return -132;
          10: return 0;
          default: return '0;
        endcase
      end
      default: return '0;
    endcase
  endfunction

endpackage : rrc_pkg
